name: CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  USERNAME: kirqe
  APP_NAME: gitops-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          IMAGE=$REGISTRY/$USERNAME/$APP_NAME
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: beget-k8s
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/gitops-deploy
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: gitops-deploy
      - name: Update manifest
        working-directory: gitops-deploy/apps/gitops-app
        run: |
          IMAGE=$REGISTRY/$USERNAME/$APP_NAME
          TAG=${GITHUB_SHA::7}
          git config --global user.email "ci@github.bot"
          git config --global user.name "CI Bot"
          sed -i "s|$IMAGE:.*|$IMAGE:$TAG|g" deployment.yaml
          git add deployment.yaml
          git commit -m "${{ github.actor }} - $APP_NAME: update image $TAG"
          git push

      - name: Deploy to k8s
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          kubectl apply -R -f gitops-deploy/apps/
