name: CI

on:
  push:
    branches:
      - main

env:
  IMAGE: ghcr.io/kirqe/gitops-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          docker build -t $IMAGE:${{ github.sha }} .
          docker push $IMAGE:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: beget-k8s
    steps:
      - uses: actions/checkout@v4
        with:
          repository: kirqe/gitops-deploy
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: gitops-deploy
      - name: Update manifest
        working-directory: gitops-deploy/gitops-app
        run: |
          git config --global user.email "ci@github.bot"
          git config --global user.name "CI Bot"
          sed -i "s|$IMAGE:.*|$IMAGE:${{ github.sha }}|g" deployment.yaml
          git add deployment.yaml
          git commit -m "update image ${{ github.sha }}"
          git push

      - name: Deploy to k8s
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          kubectl apply -f gitops-deploy/gitops-app/